import test from 'node:test';import assert from 'node:assert/strict';
import{queueConfig,queueBefore,queuePreparationUnchanged,queueCommitReconciled,currentQueuePreparation}from'./fixture-queue-processing-controls.mjs';
function config(){return{scope:'isolated-fictional-native-queue-processing',profileId:'947136fa-997b-4a83-819d-1b8bd3ecba68',role:'supervisor',cartId:'ce9cb158-bdb6-11f1-8391-8b2b4fd918b0',customerId:'a823809c-bdb6-11f1-b1be-47a66d90b06d',customerName:'Backend Test Customer A',sourceReceipt:'FXC701',sourceGRNId:'a2489c56-bdf3-11f1-97a8-8b3d06ae4c97',lotId:'a248cdd4-bdf3-11f1-97a9-efb90ed37151',orderItemId:'5e4bceea-be36-11f1-a453-ebff20c7e341',record:'FXQ992',quantity:2,expectedStock:8,artifactSHA256:'08271dada3bf90ed6912db71c0e08f95487a906d12a765bcaa706338bdf12fb7',origin:'https://backend-core.example.test',instanceId:'b0ec3933-5258-4bd5-87f4-d57b13a78971',orderProvenance:'preserved ordinary API fixture; native customer creation not accepted',sessionId:'9207d184-ddde-4d5e-bab4-cba48f73287d'};}
function snapshot(c){return{profile:{id:c.profileId,role:c.role,active:true,status:'approved'},nativeSessionPresent:true,recordAbsent:true,order:{id:c.cartId,customer_id:c.customerId,status:'OPEN',deleted_at:null},items:[{id:c.orderItemId,order_id:c.cartId,grn_items_id:c.lotId,grns_id:c.sourceGRNId,requested_quantity:2,fulfilled_quantity:0,item_status:'pending'}],lots:[{id:c.lotId,gr_id:c.sourceGRNId,qty:8,stock:8}],protectedHash:'a'.repeat(64)};}
test('queue guards accept exact API-provenance fixture and unchanged preparation',()=>{const c=config(),s=snapshot(c);assert.equal(queueBefore(c,s).status,'PASS');assert.equal(queuePreparationUnchanged(c,s,globalThis.structuredClone(s)).status,'PASS');});
test('queue refuses foreign binding, native provenance claim, depleted stock, changed request, expired session and hidden state drift',()=>{const c=config();for(const[k,v]of[['record','FXC701'],['orderProvenance','native customer creation PASS'],['quantity',3],['origin','https://backend-switch.example.test']])assert.throws(()=>queueConfig({...c,[k]:v}));for(const mutate of[s=>s.lots[0].stock=1,s=>s.items[0].requested_quantity=3,s=>s.nativeSessionPresent=false,s=>s.recordAbsent=false,s=>s.order.deleted_at='2026-10-02',s=>s.profile.role='admin']){const s=snapshot(c);mutate(s);assert.throws(()=>queueBefore(c,s));}const b=snapshot(c),a=globalThis.structuredClone(b);a.protectedHash='b'.repeat(64);assert.throws(()=>queuePreparationUnchanged(c,b,a));});

function committed(){const c=config(),b=snapshot(c);b.order.order_no='ORD-20261001-ce9cb158';b.order.updated_at='2026-10-02T19:08:43Z';b.order.updated_by='79764e1a-3aed-4cac-9a25-42ccdafb79ac';b.receipt={id:c.sourceGRNId,gr_no:c.sourceReceipt,customer_id:c.customerId,out_of_stock:false,updated_at:'2026-10-02T12:00:00Z',updated_by:b.order.updated_by};b.authHash='a'.repeat(64);b.storageHash='b'.repeat(64);b.dispatches=[];b.dispatchLines=[];b.movements=[];b.caches=[];
const tables=['goodsreceived','goodsreceived_trl','dispatch','dispatch_trl','invoice','invoice_trl','orders','order_items','stock_movements','grn_images','dispatch_images','idempotency_keys','auto_invoice_errors','customers','items','storage.objects'];b.protectedRows=Object.fromEntries(tables.map(t=>[t,[]]));for(const[t,id]of[['goodsreceived',c.sourceGRNId],['goodsreceived_trl',c.lotId],['orders',c.cartId],['order_items',c.orderItemId]])b.protectedRows[t]=[{id,sha256:'c'.repeat(64)}];b.protectedRows.invoice=[{id:'11111111-1111-4111-8111-111111111111',sha256:'d'.repeat(64)}];
const a=globalThis.structuredClone(b),d={id:'22222222-2222-4222-8222-222222222222',disp_no:c.record,customer_id:c.customerId,source_order_id:c.cartId,source_order_no:b.order.order_no,created_by:c.profileId,updated_by:c.profileId,deleted_at:null,deleted_by:null},l={id:'33333333-3333-4333-8333-333333333333',disp_id:d.id,gr_id:c.sourceGRNId,gr_trl_id:c.lotId,disp_qty:2},m={id:'44444444-4444-4444-8444-444444444444',reference_id:d.id,reference_type:'dispatch',gr_trl_id:c.lotId,movement_type:'dispatch',quantity:2,balance_before:8,balance_after:6,created_by:c.profileId},k={id:'55555555-5555-4555-8555-555555555555',rpc_function:'create_dispatch_with_stock_check',created_by:c.profileId,idempotency_key:'fictional-queue-test-key',response:{success:true,dispatch_id:d.id,source_order_cleared:true,invoice_data:{},dispatch_items:[{id:l.id,disp_qty:2,remaining_stock:6}]}};
a.recordAbsent=false;a.items=[];a.lots[0].stock=6;a.order.updated_by=c.profileId;a.order.updated_at='2026-10-02T19:40:00Z';a.receipt.updated_by=c.profileId;a.receipt.updated_at=a.order.updated_at;a.dispatches=[d];a.dispatchLines=[l];a.movements=[m];a.caches=[k];a.protectedRows.order_items=[];for(const t of['goodsreceived','goodsreceived_trl','orders'])a.protectedRows[t][0].sha256='e'.repeat(64);for(const[t,r]of[['dispatch',d],['dispatch_trl',l],['stock_movements',m],['idempotency_keys',k]])a.protectedRows[t]=[{id:r.id,sha256:'f'.repeat(64)}];return{c,b,a};}
test('one queue dispatch keeps persistent order OPEN and removes only matched item',()=>{const{c,b,a}=committed();assert.equal(queueCommitReconciled(c,b,a).status,'PASS');});
test('queue commit refuses duplicate operations, wrong stock, deleted order, changed notes, stale cache, unrelated business and auth changes',()=>{for(const mutate of[a=>a.dispatches.push({...a.dispatches[0]}),a=>a.lots[0].stock=4,a=>a.order.status='DISPATCHED',a=>a.order.deleted_at='2026-10-02',a=>a.order.note='changed',a=>a.caches[0].response.dispatch_id='66666666-6666-4666-8666-666666666666',a=>a.protectedRows.invoice[0].sha256='0'.repeat(64),a=>a.authHash='0'.repeat(64),a=>a.storageHash='0'.repeat(64),a=>a.items.push({}),a=>a.movements[0].balance_after=7]){const{c,b,a}=committed();mutate(a);assert.throws(()=>queueCommitReconciled(c,b,a));}});

test('current APK queue is a separate fresh record with exact remaining stock and preserved state',()=>{
 const {c,b,a}=committed();Object.assign(c,{currentArtifactQueue:true,record:'FXQ996',expectedStock:6,artifactSHA256:'a7df6781bdcd889eb9ccaa01ee0973890effd4d187bb6ac45f100284e1b04b69',preparationProof:'/private/new-cart-proof.json',preparationProofSHA256:'a'.repeat(64)});
 b.lots[0].stock=6;a.lots[0].stock=4;a.dispatches[0].disp_no=c.record;a.movements[0].balance_before=6;a.movements[0].balance_after=4;a.caches[0].response.dispatch_items[0].remaining_stock=4;
 assert.equal(queueCommitReconciled(c,b,a).status,'PASS');
 for(const edit of [{record:'FXQ992'},{expectedStock:8},{artifactSHA256:'a'.repeat(64)},{preparationProof:'relative'},{currentArtifactQueue:'true'}])assert.throws(()=>queueConfig({...c,...edit}));
});

test('current queue refuses unreconciled or nonordinary cart fixture preparation',()=>{
 const c={...config(),currentArtifactQueue:true,record:'FXQ996',expectedStock:6,artifactSHA256:'a7df6781bdcd889eb9ccaa01ee0973890effd4d187bb6ac45f100284e1b04b69',preparationProof:'/private/new.json',preparationProofSHA256:'a'.repeat(64)};
 const p={status:'PASS',scope:'fictional-ordinary-cart-preparation-for-APK10-queue',...Object.fromEntries(['artifactSHA256','cartId','orderItemId','lotId','quantity','expectedStock'].map(k=>[k,c[k]])),protectedStateReconciled:true,ordinaryAuthentication:true,onlyNewAPISessionLoggedOut:true,nativeCartCreationAccepted:false};
 assert.equal(currentQueuePreparation(c,p),p);
 for(const edit of [{scope:'native-cart-PASS'},{protectedStateReconciled:false},{onlyNewAPISessionLoggedOut:false},{ordinaryAuthentication:false},{orderItemId:c.cartId},{nativeCartCreationAccepted:true}])assert.throws(()=>currentQueuePreparation(c,{...p,...edit}));
});
