import test from 'node:test';import assert from 'node:assert/strict';import {normalDispatch,snapshotCase} from './fixture-normal-dispatch-controls.mjs';
const c={scope:'isolated-fictional-normal-dispatch',kind:'native-normal-dispatch',case:'same-server',backendCheckout:'/tmp/b',backendState:'/tmp/s',soakConfig:'/tmp/c',artifactAudit:'/tmp/a',caseDirectory:'/tmp/e',instanceId:'11111111-1111-1111-1111-111111111111',profileId:'22222222-2222-2222-2222-222222222222',sessionId:'33333333-3333-3333-3333-333333333333',stockLineId:'44444444-4444-4444-4444-444444444444',artifactSHA256:'a'.repeat(64),fixtureGuardSHA256:'b'.repeat(64),profileName:'Core Demo Administrator',sourceReceipt:'FXF900',sourceQuantity:10,sourcePackageMark:'',record:'FXF901',quantity:3,expectedStock:10};
test('normal partial/final cases have closed distinct numbers and exact stock budgets',()=>{normalDispatch(c);normalDispatch({...c,record:'FXF902',quantity:7,expectedStock:7});for(const change of [{record:'FXF421'},{sourceReceipt:'FXF420'},{quantity:11},{expectedStock:9},{kind:'dispatch'},{scope:'isolated-fictional-dispatch-observation'}])assert.throws(()=>normalDispatch({...c,...change}));});
test('legacy snapshot adapter cannot broaden actual native scope',()=>{assert.equal(snapshotCase(c).scope,'isolated-fictional-dispatch-observation');assert.equal(c.scope,'isolated-fictional-normal-dispatch');assert.throws(()=>snapshotCase({...c,record:'FXF431'}));});

test('committed stock, depletion flag, duplicate cache and unrelated state must reconcile',async()=>{
 const {normalAfter}=await import('./fixture-normal-dispatch-controls.mjs');const auth={profile:{id:c.profileId,name:c.profileName,role:'admin',active:true},nativeSessionPresent:true,otpCount:4,businessHash:'d'.repeat(64),otherAuthHash:'e'.repeat(64)};
 const dispatch={instanceId:c.instanceId,headerIds:[],lineIds:[],quantity:0,stock:10,cacheCount:0,invoices:0,unrelatedBusinessHash:'f'.repeat(64),sourceBound:true,sourceLineCount:1,sourceQuantity:10,sourceOutOfStock:false};const before={auth,dispatch,unrelatedCacheHash:'a'.repeat(64)};const id='55555555-5555-5555-5555-555555555555';const after={...before,dispatch:{...dispatch,headerIds:[id],lineIds:[id],quantity:3,stock:7,cacheCount:1,cacheSuccess:true,cachedHeaderId:id}};normalAfter(c,before,after,true);
 for(const change of [{sourceOutOfStock:true},{cacheCount:2},{stock:6},{unrelatedBusinessHash:'0'.repeat(64)}])assert.throws(()=>normalAfter(c,before,{...after,dispatch:{...after.dispatch,...change}},true));assert.throws(()=>normalAfter(c,before,{...after,unrelatedCacheHash:'0'.repeat(64)},true));
 const final={...c,record:'FXF902',quantity:7,expectedStock:7};const b={...before,dispatch:{...dispatch,stock:7}};const a={...after,dispatch:{...after.dispatch,quantity:7,stock:0,sourceOutOfStock:true}};normalAfter(final,b,a,true);assert.throws(()=>normalAfter(final,b,{...a,dispatch:{...a.dispatch,sourceOutOfStock:false}},true));
});

test('current supervisor normal dispatch is exact-artifact and disjoint from consumed records/fault cases',()=>{
 const current={...c,currentSupervisorDispatch:true,artifactSHA256:'a7df6781bdcd889eb9ccaa01ee0973890effd4d187bb6ac45f100284e1b04b69',profileId:'947136fa-997b-4a83-819d-1b8bd3ecba68',profileName:'New customer',instanceId:'b0ec3933-5258-4bd5-87f4-d57b13a78971',sourceReceipt:'FXF960',record:'FXF961'};normalDispatch(current);normalDispatch({...current,record:'FXF962',quantity:7,expectedStock:7});
 for(const change of [{record:'FXF901'},{record:'FXF421'},{sourceReceipt:'FXF900'},{artifactSHA256:'a'.repeat(64)},{profileName:'Core Demo Administrator'},{currentSupervisorDispatch:'true'}])assert.throws(()=>normalDispatch({...current,...change}));
});
