import test from 'node:test';import assert from 'node:assert/strict';
import{supervisorConfig,claimSupervisorWrite,reconcileSupervisorNote}from'./fixture-supervisor-realtime-controls.mjs';
const c={scope:'isolated-fictional-supervisor-realtime',origin:'https://backend-core.example.test',instanceId:'b0ec3933-5258-4bd5-87f4-d57b13a78971',cartA:'ce9cb158-bdb6-11f1-8391-8b2b4fd918b0',cartB:'f3346be6-bdb6-11f1-97b0-638c3f007281',markerA:'FixtureSupervisorRealtime0109A',markerB:'FixtureSupervisorRealtime0109B',deadlineUTC:new Date(Date.now()+60000).toISOString()};
const channels=['A','supervisor','admin'].map(role=>({role,joined:true,databaseReady:true,live:true}));
test('write claims require live controls, preserved notes and native readiness, and cannot replay',()=>{const s={status:'RUNNING',authenticationReconciled:true,nativeSupervisorReady:true,oldNotesPreserved:true,writes:[]};assert.throws(()=>claimSupervisorWrite(c,s,'A',channels.map(x=>({...x,live:false}))));assert.deepEqual(s.writes,[]);claimSupervisorWrite(c,s,'A',channels);assert.throws(()=>claimSupervisorWrite(c,s,'A',channels));claimSupervisorWrite(c,s,'B',channels);assert.throws(()=>claimSupervisorWrite(c,s,'B',channels));});
test('note reconciliation rejects unrelated stock/auth/cart changes',()=>{const before={businessHash:'business',storageHash:'storage',authHash:'auth',carts:{A:{id:c.cartA,status:'OPEN',note:'preserved A',quantity:2},B:{id:c.cartB,status:'OPEN',note:'preserved B',quantity:0}}};const after=globalThis.structuredClone(before);after.carts.A.note=c.markerA;assert.equal(reconcileSupervisorNote(c,before,before,after,'A').status,'PASS');for(const mutate of [x=>x.businessHash='changed',x=>x.authHash='changed',x=>x.carts.A.quantity++,x=>x.carts.B.note='changed']){const bad=globalThis.structuredClone(after);mutate(bad);assert.throws(()=>reconcileSupervisorNote(c,before,before,bad,'A'));}});

test('current APK Realtime mode binds fresh markers and exact audited artifact',()=>{
 const current={...c,currentArtifactRealtime:true,artifactSHA256:'a7df6781bdcd889eb9ccaa01ee0973890effd4d187bb6ac45f100284e1b04b69',markerA:'FixtureSupervisorRealtime0110A',markerB:'FixtureSupervisorRealtime0110B'};
 supervisorConfig(current);
 for(const change of [{artifactSHA256:'a'.repeat(64)},{markerA:c.markerA},{markerB:c.markerB},{currentArtifactRealtime:'true'}])assert.throws(()=>supervisorConfig({...current,...change}));
});
