import test from 'node:test';import assert from 'node:assert/strict';
import {queueCartPayload,prepareQueueCart} from './fixture-queue-cart-prepare.mjs';
import {preparationSQL} from './fixture-queue-cart-snapshot.mjs';
import {verifyPreparedCart} from './fixture-queue-cart-verify.mjs';
const c=()=>({scope:'isolated-fictional-queue-cart-preparation',artifactSHA256:'a7df6781bdcd889eb9ccaa01ee0973890effd4d187bb6ac45f100284e1b04b69',nativeSessionId:'80417ab6-d156-4433-8285-2b0e80056b03',cartId:'ce9cb158-bdb6-11f1-8391-8b2b4fd918b0',customerId:'a823809c-bdb6-11f1-b1be-47a66d90b06d',lotId:'a248cdd4-bdf3-11f1-97a9-efb90ed37151',quantity:2,expectedStock:6,record:'FXQ996',deadlineUTC:new Date(Date.now()+300000).toISOString()});
test('cart preparation refuses aliases, wrong stock and noncurrent artifacts before authentication',()=>{const x=c();assert.equal(queueCartPayload(x).p_quantity,2);for(const edit of [{record:'FXQ992'},{quantity:3},{expectedStock:8},{artifactSHA256:'a'.repeat(64)},{scope:'production'}])assert.throws(()=>queueCartPayload({...x,...edit}));});
test('preparation SQL protects source stock, old successes and all unrelated auth while admitting only target cart',()=>{const x=c(),sql=preparationSQL(x);assert.match(sql,/READ ONLY/);assert.doesNotMatch(sql,/UPDATE |INSERT |DELETE /);assert.match(sql,/mobile='919888888872'/);assert.match(sql,/WHERE id<>'ce9cb158/);assert.match(sql,/goodsreceived/);assert.match(sql,/warehouse_security.refresh_sessions/);});
test('uncertain cart write stops once without logout, replay or cleanup',async()=>{const x=c(),state={authAttempts:0,cartAttempts:0},b={recordAbsent:true,customerActive:true,customerRole:'customer',nativeSessionPresent:true,items:[],order:{id:x.cartId,status:'OPEN'},lot:{stock:6},quota:{hourly:0,daily:0}};let writes=0,logouts=0;const d={verifyOwnership:async()=>{},snapshot:async()=>b,evidence:async()=>{},record:async()=>{},authenticate:async()=>({access:'private-memory',refresh:'private-memory',sessionId:x.nativeSessionId}),verifyAuthentication:async()=>{},cart:async()=>{writes++;throw new Error('uncertain');},logout:async()=>{logouts++;}};await assert.rejects(prepareQueueCart(x,d,state));assert.equal(writes,1);assert.equal(logouts,0);assert.equal(state.cartAttempts,1);assert.equal(state.authAttempts,1);});
test('cart reconciliation rejects wrong quantity and changed notes or unrelated stock',()=>{const x=c(),b={unrelatedRowsHash:'a',unrelatedAuthHash:'b',storageHash:'c',customerStaticHash:'d',nativeSessionPresent:true,recordAbsent:true,lot:{stock:6},authHash:'e',items:[],order:{id:x.cartId,status:'OPEN',note:'preserved',updated_by:'79764e1a-3aed-4cac-9a25-42ccdafb79ac'}};const a={...b,items:[{id:'11111111-1111-4111-8111-111111111111',order_id:x.cartId,grn_items_id:x.lotId,grns_id:'a2489c56-bdf3-11f1-97a8-8b3d06ae4c97',requested_quantity:2,fulfilled_quantity:0,item_status:'pending'}]};verifyPreparedCart(x,b,a,{success:true});for(const mutate of [v=>v.items[0].requested_quantity=3,v=>v.order.note='changed',v=>v.lot.stock=5,v=>v.unrelatedRowsHash='changed']){const v=globalThis.structuredClone(a);mutate(v);assert.throws(()=>verifyPreparedCart(x,b,v,{success:true}));}});
