import test from 'node:test';import assert from 'node:assert/strict';import{spawnSync}from'node:child_process';import{fileURLToPath}from'node:url';
import{bGRNPDFConfig,bGRNPDFHeader,bGRNPDFQuery,bGRNPDFBefore}from'./fixture-b-grn-pdf-controls.mjs';import{navigationSnapshotSQL,navigationBefore}from'./fixture-navigation-guards.mjs';
const c={scope:'isolated-fictional-navigation-case',case:'customer-b-grn-pdf',kind:'native-customer-b-grn-pdf',customerBGRNPDF:true,profileId:'34d9d337-ec2e-4bed-b555-0e8b63dd3aef',profileName:'Customer B',sessionId:'00000000-0000-4000-8000-000000000001',origin:'https://backend-core.example.test',instanceId:'b0ec3933-5258-4bd5-87f4-d57b13a78971',grnId:'a24c256a-bdf3-11f1-97aa-57de57b8fb69',grnNumber:'FXC702',artifactSHA256:'08271dada3bf90ed6912db71c0e08f95487a906d12a765bcaa706338bdf12fb7',fixtureGuardSHA256:'a'.repeat(64),backendCheckout:'/owned/backend',backendState:'/owned/state',soakConfig:'/private/ui',artifactAudit:'/private/audit',caseDirectory:'/private/new'};
test('B GRN PDF binds genuine customer, receipt, role and artifact without adding invoice or write permissions',()=>{
 bGRNPDFConfig(c);assert.equal(bGRNPDFHeader(c).number,'FXC702');for(const edit of [{grnNumber:'FXC701'},{grnId:c.instanceId},{kind:'native-pdf-send'},{customerBGRNPDF:false},{reservedCustomerPDF:true},{customerBImageRead:true},{customerBLogout:true},{customerBInvoiceDenial:true},{artifactSHA256:'b'.repeat(64)}])assert.throws(()=>bGRNPDFConfig({...c,...edit}));
 const sql=navigationSnapshotSQL(c);assert.match(sql,/mobile='919888888873'/);assert.doesNotMatch(sql,/\b(INSERT|UPDATE|DELETE|TRUNCATE)\b/i);
 const s={profile:{id:c.profileId,name:'Customer B',role:'customer',active:true},nativeSessionPresent:true,otpCount:1,businessHash:'a'.repeat(64),otherAuthHash:'b'.repeat(64)};navigationBefore(c,s);assert.throws(()=>navigationBefore(c,{...s,profile:{...s.profile,active:false}}));assert.throws(()=>navigationBefore(c,{...s,nativeSessionPresent:false}));
});
test('B document text checks reject another receipt/customer and mixed content',()=>{const q=spawnSync('python3',[fileURLToPath(new URL('./fixture-ui/test_b_grn_pdf_controls.py',import.meta.url))],{encoding:'utf8',timeout:10000});assert.equal(q.status,0,q.stderr);});

test('B PDF SQL and admission require genuine active assignment and keep all other documents in the protected digest',()=>{
 const {sql,prefix}=bGRNPDFQuery(c);assert.equal(prefix,'grn/'+c.grnId+'/');assert.match(sql,/REPEATABLE READ READ ONLY/);assert.match(sql,/statement_timeout='10s'/);assert.ok(sql.includes("WHERE NOT (bucket_id='documents' AND name LIKE '"+prefix+"%')"));assert.doesNotMatch(sql,/\b(INSERT|UPDATE|DELETE|ALTER|TRUNCATE)\b/i);
 const snapshot={profile:{id:c.profileId,name:'Customer B',role:'customer',active:true},nativeSessionPresent:true,otpCount:1,businessHash:'a'.repeat(64),otherAuthHash:'b'.repeat(64)};bGRNPDFBefore(c,snapshot,{header:bGRNPDFHeader(c)});assert.throws(()=>bGRNPDFBefore(c,snapshot,{header:{...bGRNPDFHeader(c),assigned:false}}));assert.throws(()=>bGRNPDFBefore(c,{...snapshot,profile:{...snapshot.profile,active:false}},{header:bGRNPDFHeader(c)}));
});
