import test from 'node:test';import assert from 'node:assert/strict';import{spawnSync}from'node:child_process';import{fileURLToPath}from'node:url';
import{bNativeImageConfig,bNativeImageFixture,bNativeImageTarget,bImageHTTPCounts}from'./fixture-b-native-image-controls.mjs';import{navigationSnapshotSQL,navigationBefore}from'./fixture-navigation-guards.mjs';
const c={scope:'isolated-fictional-navigation-case',case:'customer-b-image-read',kind:'native-customer-b-image-read',customerBImageRead:true,profileId:'34d9d337-ec2e-4bed-b555-0e8b63dd3aef',profileName:'Customer B',sessionId:'00000000-0000-4000-8000-000000000001',origin:'https://backend-core.example.test',instanceId:'b0ec3933-5258-4bd5-87f4-d57b13a78971',targetReceiptId:'a24c256a-bdf3-11f1-97aa-57de57b8fb69',artifactSHA256:'08271dada3bf90ed6912db71c0e08f95487a906d12a765bcaa706338bdf12fb7',fixtureGuardSHA256:'a'.repeat(64),backendCheckout:'/owned/backend',backendState:'/owned/state',soakConfig:'/private/ui',artifactAudit:'/private/audit',caseDirectory:'/private/new',imageId:'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',imagePath:'headers/a24c256a-bdf3-11f1-97aa-57de57b8fb69/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb_fixture-b-0109.png',imageSHA256:'d4575f91c6f9ed6eac9dc6da8fca4d5a016fe481c4e82887bbba35f98f83029d'};
test('native B rendering binds only genuine B scope, preserves role and requires actual confirmed fixture proof',()=>{
 bNativeImageConfig(c);for(const edit of [{profileName:'New customer'},{artifactSHA256:'b'.repeat(64)},{imagePath:'headers/foreign/image.png'},{customerBImageRead:false},{reservedCustomerReceiptDenial:true},{customerBInvoiceDenial:true},{customerBLogout:true},{kind:'native-receipt-denial'}])assert.throws(()=>bNativeImageConfig({...c,...edit}));
 const image={id:c.imageId,grnId:c.targetReceiptId,path:c.imagePath,status:'confirmed',tokenPresent:false,fileSize:160,mimeType:'image/png'},proof={status:'PASS',imageSHA256:c.imageSHA256,final:{images:[image]},confirmed:{images:[image]}};bNativeImageFixture(c,proof);assert.throws(()=>bNativeImageFixture(c,{...proof,final:{images:[{...image,status:'pending'}]}}));assert.throws(()=>bNativeImageFixture(c,{...proof,status:'PREPARED'}));
 const target={receiptId:c.targetReceiptId,record:'FXC702',customerId:'a8246002-bdb6-11f1-b1bf-07b1deb5bca2',assigned:true,images:[{id:c.imageId,path:c.imagePath,status:'confirmed',tokenPresent:false,size:160,mime:'image/png'}]};bNativeImageTarget(c,target);assert.throws(()=>bNativeImageTarget(c,{...target,assigned:false}));
 assert.match(navigationSnapshotSQL(c),/mobile='919888888873'/);const s={profile:{id:c.profileId,name:'Customer B',role:'customer',active:true},nativeSessionPresent:true,otpCount:1,businessHash:'a'.repeat(64),otherAuthHash:'b'.repeat(64)};navigationBefore(c,s);assert.throws(()=>navigationBefore(c,{...s,profile:{...s.profile,active:false}}));assert.throws(()=>navigationBefore(c,{...s,nativeSessionPresent:false}));
});
test('image HTTP evidence matches only the declared signed image read and removes credentials/queries',()=>{
 const raw='"GET /storage/v1/object/sign/grn-images/'+c.imagePath+'?token=PRIVATE_SIGNED_VALUE HTTP/1.1" 200\n"GET /storage/v1/object/sign/grn-images/foreign.png?token=OTHER HTTP/1.1" 200';const counts=bImageHTTPCounts(c,raw);assert.deepEqual(counts,{successful:1,failed:0});assert.doesNotMatch(JSON.stringify(counts),/PRIVATE|token|OTHER/);assert.deepEqual(bImageHTTPCounts(c,raw.replace('" 200','" 403')),{successful:0,failed:1});
});
test('native screenshot matcher requires the exact visible checkerboard and rejects ambiguity',()=>{
 const q=spawnSync('/usr/bin/python3',[fileURLToPath(new URL('./fixture-ui/test_b_image_render_controls.py',import.meta.url))],{encoding:'utf8',timeout:20000});assert.equal(q.status,0,q.stderr);
});
