import test from 'node:test';import assert from 'node:assert/strict';import {runDispatchConcurrency} from './fixture-dispatch-concurrency-run.mjs';
const c={scope:'isolated-fictional-native-dispatch-concurrency',origin:'https://backend-core.example.test',instanceId:'b0ec3933-5258-4bd5-87f4-d57b13a78971',artifactSHA256:'a7df6781bdcd889eb9ccaa01ee0973890effd4d187bb6ac45f100284e1b04b69',profileId:'947136fa-997b-4a83-819d-1b8bd3ecba68',competitorProfileId:'f94caa4f-0051-4660-920a-5f41aac86fa7',customerId:'a823809c-bdb6-11f1-b1be-47a66d90b06d',record:'FXQ994',competitorRecord:'FXQ995',sourceReceipt:'FXQ993',sourceQuantity:3,quantity:2,expectedStock:3,lotId:'400e423c-bea4-11f1-903b-c7dfaaa1d594',sourceGRNId:'400db20e-bea4-11f1-903a-6ffba93074e5',sessionId:'9207d184-ddde-4d5e-bab4-cba48f73287d',deadlineUTC:'2099-01-01T00:00:00Z'};
function adapter(failure){const calls=[];let changed=false;return {calls,verifyOwnership:async()=>{},snapshot:async()=>({stock:3,nativeRecordCount:0,competitorRecordCount:0,lotBound:true,nativeSessionPresent:true,changed}),evidence:async()=>{},authenticate:async()=>({access:'memory',refresh:'memory',sessionId:'new'}),verifyAuthentication:async()=>{},native:async phase=>{calls.push(phase);if(phase==='prepare'&&failure==='prepare')changed=true;return{status:'NATIVE_ERROR_OBSERVED',submissionAttempts:1};},transportBaseline:async()=>0,record:async()=>{},waitForHold:async()=>{calls.push('HOLD');if(failure==='hold')throw new Error('No actual hold');return{event:'dispatch-request-delay-start',delayMs:5000};},competitor:async()=>{calls.push('WRITE');throw new Error('Uncertain');},logout:async()=>calls.push('LOGOUT'),cleanupNative:async()=>calls.push('CLEANUP')};}
test('competitor cannot start without actual native hold',async()=>{const d=adapter('hold'),s={nativeAttempts:0,competitorAttempts:0};await assert.rejects(()=>runDispatchConcurrency(c,d,s));assert.equal(s.nativeAttempts,1);assert.equal(s.competitorAttempts,0);assert.ok(!d.calls.includes('WRITE'));assert.ok(!d.calls.includes('LOGOUT'));});
test('uncertain competitor consumes one attempt and never cleans or retries',async()=>{const d=adapter(),s={nativeAttempts:0,competitorAttempts:0};await assert.rejects(()=>runDispatchConcurrency(c,d,s));assert.equal(s.competitorAttempts,1);assert.equal(d.calls.filter(x=>x==='WRITE').length,1);assert.ok(d.calls.indexOf('HOLD')<d.calls.indexOf('WRITE'));assert.ok(!d.calls.includes('LOGOUT')&&!d.calls.includes('CLEANUP'));});
test('backend mutation during native preparation stops before either write',async()=>{const d=adapter('prepare'),s={nativeAttempts:0,competitorAttempts:0};await assert.rejects(()=>runDispatchConcurrency(c,d,s));assert.equal(s.nativeAttempts,0);assert.equal(s.competitorAttempts,0);assert.ok(!d.calls.includes('submit')&&!d.calls.includes('WRITE'));});
function renewingAdapter(extra={}){const d=adapter('hold');let rotated=false;const b={stock:3,nativeRecordCount:0,competitorRecordCount:0,lotBound:true,nativeSessionPresent:true,nativeSessionId:c.sessionId,nativeSessionIssuedUTC:'2026-10-02T18:37:01Z',nativeSessionExpiryUTC:'2026-10-09T18:37:01Z',authHash:'a'.repeat(64),unrelatedAuthHash:'b'.repeat(64),storageHash:'c'.repeat(64)};d.snapshot=async()=>rotated?{...b,authHash:'d'.repeat(64),unrelatedAuthHash:'e'.repeat(64),...extra}:b;d.native=async phase=>{d.calls.push(phase);if(phase==='prepare')rotated=true;return{status:'NATIVE_ERROR_OBSERVED',submissionAttempts:1};};d.renewalProof=async(before,after,beforeUTC,afterUTC)=>{d.calls.push('ROTATION_PROOF');return{scope:'readonly-native-refresh-rotation-proof',status:'PASS',sessionId:c.sessionId,beforeAuthHash:before.authHash,afterAuthHash:after.authHash,beforeUTC,afterUTC,matchingPriorNativeRotationHashes:1,refreshHTTPCount:1,refreshHTTPStatus:200,refreshAtUTC:beforeUTC,sessionIssuedUTC:b.nativeSessionIssuedUTC,sessionExpiryUTC:b.nativeSessionExpiryUTC};};return d;}
test('independently bound renewal can pass preparation but cannot bypass actual hold',async()=>{const d=renewingAdapter(),s={nativeAttempts:0,competitorAttempts:0};await assert.rejects(()=>runDispatchConcurrency(c,d,s));assert.ok(d.calls.includes('ROTATION_PROOF'));assert.equal(s.nativeAttempts,1);assert.equal(s.competitorAttempts,0);assert.ok(!d.calls.includes('WRITE'));});
test('renewal evidence cannot hide stock mutation during preparation',async()=>{const d=renewingAdapter({stock:1}),s={nativeAttempts:0,competitorAttempts:0};await assert.rejects(()=>runDispatchConcurrency(c,d,s));assert.equal(s.nativeAttempts,0);assert.equal(s.competitorAttempts,0);});
