import test from 'node:test';import assert from 'node:assert/strict';import{authenticateSupervisorAccount,logoutSupervisorAccount}from'./fixture-supervisor-realtime-auth.mjs';
function fixture(fault){
 const c={scope:'isolated-fictional-supervisor-realtime',origin:'https://backend-core.example.test',instanceId:'b0ec3933-5258-4bd5-87f4-d57b13a78971',cartA:'ce9cb158-bdb6-11f1-8391-8b2b4fd918b0',cartB:'f3346be6-bdb6-11f1-97b0-638c3f007281',markerA:'FixtureSupervisorRealtime0109A',markerB:'FixtureSupervisorRealtime0109B',deadlineUTC:new Date(Date.now()+60000).toISOString()};
 const ids={A:'79764e1a-3aed-4cac-9a25-42ccdafb79ac',supervisor:'947136fa-997b-4a83-819d-1b8bd3ecba68',admin:'f94caa4f-0051-4660-920a-5f41aac86fa7'};
 const s={nativeSupervisorSessionPresent:true,businessHash:'business',storageHash:'storage',unrelatedAuthHash:'other',carts:{A:{note:'old A'},B:{note:'old B'}},participants:{}};
 for(const role of Object.keys(ids))s.participants[role]={profile:{id:ids[role],role:role==='admin'?'admin':role==='supervisor'?'supervisor':'customer',active:true},staticHash:'static',sessions:[{id:'old-'+role,rowSHA256:'old'}],verifiedOTPs:0,quota:{hourly:0,daily:0}};
 const state={authAttempts:[],apiSessionIds:{},logoutAttempts:[]},calls=[],events=[];const newId='11111111-1111-4111-8111-111111111111';
 const d={verifyOwnership:async()=>{},snapshot:async()=>globalThis.structuredClone(s),evidence:async()=>{},record:async e=>events.push(e),challenge:async()=> '123456',call:async route=>{
  calls.push(route);if(route.endsWith('/request')){if(fault==='timeout')throw new Error('uncertain request');return {body:{success:true}};}
  if(route.endsWith('/verify')){const p=s.participants.A;p.verifiedOTPs++;p.quota.hourly++;p.quota.daily++;p.sessions.push({id:newId,issuedAt:new Date().toISOString(),expiresAt:new Date(Date.now()+86400000).toISOString(),rowSHA256:'a'.repeat(64)});if(fault==='old-session')s.participants.supervisor.sessions[0].rowSHA256='changed';return {status:200,body:{success:true,data:{user:{id:ids.A,role:'customer',active:true},session:{access_token:'mock-access',refresh_token:'mock-refresh'}}}};}
  if(route.endsWith('/logout_session')){s.participants.A.sessions=s.participants.A.sessions.filter(x=>x.id!==newId);return {body:true};}throw new Error('unexpected request');
 }};return {c,s,state,d,calls,events};
}
test('ordinary authentication preserves old sessions; cleanup requires accepted case and only the new session',async()=>{const f=fixture(),credentials=await authenticateSupervisorAccount(f.c,'A',f.d,f.state);assert.equal(f.s.participants.A.sessions.length,2);await assert.rejects(logoutSupervisorAccount(f.c,'A',credentials,f.d,f.state));f.state.acceptanceReconciled=true;await assert.rejects(logoutSupervisorAccount(f.c,'A',{...credentials,sessionId:'old-A'},f.d,f.state));await logoutSupervisorAccount(f.c,'A',credentials,f.d,f.state);assert.deepEqual(f.s.participants.A.sessions,[{id:'old-A',rowSHA256:'old'}]);await assert.rejects(logoutSupervisorAccount(f.c,'A',credentials,f.d,f.state));assert.equal(f.calls.filter(x=>x.endsWith('/logout_session')).length,1);});
test('uncertain OTP or changed old session preserve failure and prohibit authentication replay or cleanup',async()=>{for(const fault of ['timeout','old-session']){const f=fixture(fault);await assert.rejects(authenticateSupervisorAccount(f.c,'A',f.d,f.state));await assert.rejects(authenticateSupervisorAccount(f.c,'A',f.d,f.state));assert.equal(f.calls.filter(x=>x.endsWith('/request')).length,1);assert.ok(!f.calls.some(x=>x.endsWith('/logout_session')));assert.equal(f.events.at(-1).phase,'AUTH_STOPPED_NO_REPLAY_OR_CLEANUP');}});
test('exhausted ordinary quota refuses before consuming OTP',async()=>{const f=fixture();f.s.participants.A.quota.hourly=5;await assert.rejects(authenticateSupervisorAccount(f.c,'A',f.d,f.state));assert.deepEqual(f.calls,[]);assert.deepEqual(f.state.authAttempts,[]);});

test('literal staff or customer cannot stand in for the actual supervisor; refuse before OTP',async()=>{for(const role of ['staff','customer']){const f=fixture();f.s.participants.supervisor.profile.role=role;await assert.rejects(authenticateSupervisorAccount(f.c,'supervisor',f.d,f.state));assert.deepEqual(f.calls,[]);assert.deepEqual(f.state.authAttempts,[]);}});
