import test from 'node:test';import assert from 'node:assert/strict';import {prepareBInvoiceFixture} from './fixture-b-invoice-preparation-run.mjs';
const id='11111111-1111-4111-8111-111111111111';
const c={scope:'isolated-fictional-b-invoice-preparation',artifactSHA256:'a7df6781bdcd889eb9ccaa01ee0973890effd4d187bb6ac45f100284e1b04b69',origin:'https://backend-core.example.test',instanceId:'b0ec3933-5258-4bd5-87f4-d57b13a78971',customerId:'a8246002-bdb6-11f1-b1bf-07b1deb5bca2',customerName:'Backend Test Customer B',receiptNumber:'FXI971',dispatchNumber:'FXI972',invoiceNumber:20261031,financialYear:2026,noAutomaticRetry:true,attempt:1,durationMode:'legacy',itemId:id,receiptDate:'2026-10-01T12:00:00Z',dispatchDate:'2026-10-03T12:00:00Z',deadlineUTC:new Date(Date.now()+540000).toISOString(),receiptKey:'fixture-b-invoice-receipt-'+id,dispatchKey:'fixture-b-invoice-dispatch-'+id};
test('uncertain receipt transport preserves evidence and prevents dispatch, invoice, replay and cleanup',async()=>{
 const before={receiptAbsent:true,adminActive:true,adminRole:'admin',unrelatedRowsHash:'business',unrelatedAuthHash:'other-auth',storageHash:'bytes',adminStaticHash:'profile',receipts:[],lots:[],movements:[],caches:[],dispatches:[],dispatchLines:[],dispatchMovements:[],invoices:[],invoiceLines:[],verifiedOTPs:2,quota:{hourly:0,daily:2},adminSessions:[{id:'old',hash:'unchanged'}]};
 const after={...before,verifiedOTPs:3,quota:{hourly:1,daily:3},adminSessions:[...before.adminSessions,{id:'new',hash:'new'}]};let snapshots=0,calls=0,logouts=0;const evidence=[],phases=[];const state={attempts:{authentication:0,receipt:0,dispatch:0,invoice:0}};
 await assert.rejects(prepareBInvoiceFixture(c,{verifyOwnership:async()=>{},snapshot:async()=>snapshots++===0?before:after,evidence:async(n,s)=>evidence.push([n,s]),record:async p=>phases.push(p),authenticate:async()=>({sessionId:'new',access:'memory-only',refresh:'memory-only'}),call:async label=>{assert.equal(label,'receipt');calls++;throw new Error('Response lost');},preview:async()=>assert.fail('Preview after uncertain write'),logout:async()=>{logouts++;}},state),/Response lost/);
 assert.equal(calls,1);assert.equal(logouts,0);assert.deepEqual(state.attempts,{authentication:1,receipt:1,dispatch:0,invoice:0});assert.ok(evidence.some(([n])=>n==='uncertain-receipt'));assert.ok(phases.includes('UNCERTAIN_WRITE_NO_REPLAY_OR_CLEANUP'));assert.equal(state.allWritesReconciled,undefined);
});
