import test from 'node:test';import assert from 'node:assert/strict';
import {runRealtime} from './fixture-realtime-run.mjs';
const id=n=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
function fixture(failure){
 const c={scope:'isolated-fictional-native-realtime',origin:'https://backend-core.example.test',instanceId:'b0ec3933-5258-4bd5-87f4-d57b13a78971',profileId:'947136fa-997b-4a83-819d-1b8bd3ecba68',callerPhone:'919888888872',orderId:'ce9cb158-bdb6-11f1-8391-8b2b4fd918b0',record:'FXC701',quantities:[1,2],manualRefreshDuringObservation:false,sessionId:id(1),stockLineId:id(2),customerId:id(3),callerProfileId:id(4),soakConfig:'/private/ui',caseDirectory:'/private/new',prerequisiteEvidence:'/private/proof',otpSocket:'/private/socket'};
 const base={nativeProfile:{id:c.profileId,role:'customer',active:true,name:'New customer'},nativeSessionPresent:true,callerProfile:{id:c.callerProfileId,role:'customer',active:true,name:'Customer A'},stock:{id:c.stockLineId,customerId:c.customerId,record:c.record,stock:8,qty:8},cart:{id:c.orderId,customerId:c.customerId,status:'OPEN',revisions:[]},items:[],businessHash:'a'.repeat(64),otherAuthHash:'b'.repeat(64),cartStaticHash:'c'.repeat(64),callerSessions:[{id:id(8),rowHash:'d'.repeat(64)},{id:id(9),rowHash:'e'.repeat(64)}]};
 let actual=structuredClone(base),phase=0;const saved=[],calls=[],sent=[],events=[{status:'READY',window:'foreground',manualRefreshUsed:false},{status:'DELIVERED',phase:'added',manualRefreshUsed:false},{status:'READY',window:'reconnected',manualRefreshUsed:false,ownedNetworkRestored:true},{status:'DELIVERED',phase:'edited',manualRefreshUsed:false},{status:'PASS',scope:'native-realtime-foreground-and-reconnect'}];
 const state={status:'RUNNING',writes:[]};
 const d={authenticate:async()=>({access:'private-access',refresh:'private-refresh',sessionId:id(9),baseline:base}),receive:async()=>{const v=events.shift();if(failure==='native'&&v.status==='DELIVERED')return {status:'FAIL'};return v;},save:async s=>saved.push(structuredClone(s)),evidence:async()=>{},send:async x=>sent.push(x),snapshot:async()=>structuredClone(actual),stopNative:async()=>{},waitNative:async()=>{},call:async(path,body,access)=>{
  calls.push({path,body,access});if(path.endsWith('logout_session')){actual.callerSessions=actual.callerSessions.filter(s=>s.id!==id(9));return true;}
  phase++;assert.equal(saved.at(-1).writes.at(-1).status,'ATTEMPTED_NO_REPLAY');
  actual.items=[{id:id(5),stockLineId:c.stockLineId,quantity:phase,fulfilled:0}];actual.cart.revisions.push({by:c.callerProfileId,action:'UPDATE',cart_items:[{quantity:phase}]});
  if(failure==='transport')throw new Error('lost response');return id(5);
 }};return {c,d,state,saved,calls,sent};
}
test('two native-delivered writes are persisted before HTTP and only the new caller logs out',async()=>{const h=fixture();const result=await runRealtime(h.c,h.d,h.state);assert.equal(result.status,'PASS');assert.equal(h.calls.length,3);assert.equal(h.sent.length,2);assert.equal(h.calls[1].body.p_order_item_id,id(5));assert.equal(h.calls[2].access,undefined);assert.doesNotMatch(JSON.stringify(h.saved),/private-access|private-refresh/);});
test('lost write response reconciles but never replays or starts the dependent edit',async()=>{const h=fixture('transport');await assert.rejects(runRealtime(h.c,h.d,h.state),/WRITE_RESPONSE_UNCERTAIN_RECONCILED_NO_REPLAY/);assert.equal(h.calls.filter(x=>!x.path.endsWith('logout_session')).length,1);assert.equal(h.sent.length,0);});
test('native delivery refusal stops the second write and preserves the attempted marker',async()=>{const h=fixture('native');await assert.rejects(runRealtime(h.c,h.d,h.state));assert.equal(h.calls.filter(x=>!x.path.endsWith('logout_session')).length,1);assert.equal(h.saved.findLast(x=>x.writes.length)?.writes[0].status,'ATTEMPTED_NO_REPLAY');});
